# Generated by Django 5.1.4 on 2025-01-06 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 6, 20, 25, 33, 112044)),
            preserve_default=False,
        ),
    ]
